#pragma once
#define VIRTUALKD_VERSION 		 2,6,0,1
#define VIRTUALKD_VERSION_STR 	"2.6"
#define COPYRIGHT_STR			"LGPL"
#define TRADEMARKS_STR			"SysProgs.org"
#define PRODUCTNAME_STR			"VitualKD"
#define COMPANY_STR				"SysProgs.org"
#define COMMENTS_STR			"http://virtualkd.sysprogs.org/"
#define VIRTUALKD_VER_INT		0x02600000

#define KDCLIENT_DLL_VER_STR	VIRTUALKD_VERSION_STR
#define KDCLIENT_DLL_VER		VIRTUALKD_VERSION

#define VMXPATCH_EXE_VER_STR	VIRTUALKD_VERSION_STR
#define VMXPATCH_EXE_VER		VIRTUALKD_VERSION

#define VMMON_EXE_VER_STR		VIRTUALKD_VERSION_STR
#define VMMON_EXE_VER			VIRTUALKD_VERSION

#define VMINSTALL_EXE_VER_STR	VIRTUALKD_VERSION_STR
#define VMINSTALL_EXE_VER		VIRTUALKD_VERSION

#define KERNEL_PART_VER			2,0,0,1
#define KERNEL_PART_VER_STR		"2.0"

#define KDPATCH_SYS_VER_STR		KERNEL_PART_VER_STR
#define KDPATCH_SYS_VER			KERNEL_PART_VER

#define KDVM_DLL_VER_STR		KERNEL_PART_VER_STR
#define KDVM_DLL_VER			KERNEL_PART_VER
