# VCMON.mak - makefile for VxD VCMON

DEVICENAME = VCMON
DYNAMIC    = 1
TARGET     = WIN40
DEBUGGER   = SOFTICE
FRAMEWORK  = C
DEBUG      = 1
OBJECTS    = vcmon.OBJ

all:	$(DEVICENAME).vxd 
	copy 	*.vxd ..\windebug\.
	copy	*.vxd ..\.

!include $(VTOOLSD)\include\vtoolsd.mak
!include $(VTOOLSD)\include\vxdtarg.mak

vcmon.OBJ:	vcmon.c vcmon.h