//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VXDMON.RC
//
#define IDM_EXIT                        104
#define IDM_SAMPLE                      105
#define IDM_ABOUT                       300
#define ID_LISTVIEW                     1000
#define ID_TREEVIEW                     1001
#define ID_CALLVIEW                     1002
#define IDM_TREEVIEW                    40002
#define IDM_SAVE                        40007
#define IDM_ANCESTORS                   40008
#define IDM_DESCENDANTS                 40009
#define IDM_OVERHEAD                    40010
#define IDM_IGNORE                      40011
#define IDM_SAVEAS                      40012
#define IDM_CALLSAVE                    40014
#define IDM_GETZEROSTATS                40015
#define IDM_RESETONUPDATE               40015
#define IDM_ZEROSTATS                   40016
#define IDM_HELP                        40017
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
