//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cacheset.rc
//
#define IDDEFAULT                       3
#define IDCLEAR                         5
#define IDC_MINIMUM                     1000
#define IDC_MAXIMUM                     1001
#define IDAPPLY                         1002
#define IDC_CURRENT                     1003
#define IDC_PEAK                        1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
