//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vcmon.rc
//
#define IDABOUT                         2
#define IDRESET                         3
#define IDRATE                          4
#define IDB_LOGO                        104
#define IDB_SMLOGO                      105
#define IDC_FRAME                       1000
#define IDC_SLIDE                       1001
#define IDC_GRCOMPBUF                   1015
#define IDC_GRSIZE                      1015
#define IDC_GRFAULTS                    1017
#define IDC_GRPGS                       1018
#define IDC_GRHITS                      1018
#define IDC_MEMSIZE                     1019
#define IDC_VCSIZE                      1019
#define IDC_COMPBUF                     1020
#define IDC_GRREP                       1020
#define IDC_COMPRATIO                   1021
#define IDC_GRNEW                       1021
#define IDC_DISK                        1022
#define IDC_VCNEW                       1022
#define IDC_FREEMEM                     1023
#define IDC_GRHOLD                      1023
#define IDC_PGRAM                       1024
#define IDC_VCHIT                       1024
#define IDC_PGDISK                      1025
#define IDC_VCMISS                      1025
#define IDC_DISKWRITE                   1026
#define IDC_VCHOLD                      1026
#define IDC_CACHEHIT                    1027
#define IDC_VCREPHIT                    1027
#define IDC_PGINS                       1028
#define IDC_VCREPMISS                   1028
#define IDC_PGOUTS                      1029
#define IDC_GRPGFLT                     1029
#define IDC_DISKREAD                    1030
#define IDC_VCPGREAD                    1030
#define IDC_COMPTIME                    1031
#define IDC_VCPGWRITE                   1031
#define IDC_DISKTIME                    1032
#define IDC_VCHITRATE                   1032
#define IDC_TIMES                       1033
#define IDC_VCFREE                      1033
#define IDC_CACHEMISS                   1034
#define IDC_CACHE                       1035
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
